version: '3.5'
services:
  sishi_graphql:
    container_name: sishi_graphql
    environment:
      POSTGRES_DB: sishi_graphql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    image: postgres:latest
    volumes:
      - ./:/var/lib/docker/volumes/
    ports:
      - 5436:5432